- name: Ensure PostgreSQL {{ pg_version }} installed
  apt:
    name:
      - "postgresql-{{ pg_version }}"
      - "postgresql-client-{{ pg_version }}"
    state: present
    update_cache: true

- name: Set listen_addresses='*'
  lineinfile:
    path: "/etc/postgresql/{{ pg_version }}/main/postgresql.conf"
    regexp: '^[#\s]*listen_addresses\s*='
    line: "listen_addresses = '*'"
  notify: restart postgres

- name: Ensure port 5432 (optional)
  lineinfile:
    path: "/etc/postgresql/{{ pg_version }}/main/postgresql.conf"
    regexp: '^[#\s]*port\s*='
    line: "port = 5432"
  notify: restart postgres

- name: Manage pg_hba (ACLs)
  blockinfile:
    path: "/etc/postgresql/{{ pg_version }}/main/pg_hba.conf"
    marker: "# {mark} ansible app access"
    block: |
      {% for cidr in allow_cidrs %}
      host  all  all  {{ cidr }}  md5
      {% endfor %}
  notify: reload postgres  # pg_hba can be reloaded (no full restart)

- name: Manage pg_hba (specific allows first)
  blockinfile:
    path: "/etc/postgresql/{{ pg_version }}/main/pg_hba.conf"
    marker: "# {mark} ansible app access"
    # Ensure our block sits near the top for precedence
    insertbefore: BOF
    block: |
      # Allow Vault to manage creds on {{ app_db }}
      {% for cidr in allow_cidrs %}
      host    {{ app_db }}   {{ super_user }}   {{ cidr }}      {{ pg_hba_method }}
      {% endfor %}
      # Allow kube workloads to access {{ app_db }}
      {% for cidr in allow_cidrs %}
      host    {{ app_db }}   all                {{ cidr }}   {{ pg_hba_method }}
      {% endfor %}  
  notify: reload postgres


- name: Ensure service running/enabled
  service:
    name: "postgresql@{{ pg_version }}-main"
    state: started
    enabled: true

# Local socket wait (doesn't require network bind)
- name: Wait for 5432 locally
  wait_for:
    port: 5432
    timeout: 30
