---
- name: Install PostgreSQL {{ pg_version }} + client & driver
  apt:
    name:
      - "postgresql-{{ pg_version }}"
      - "postgresql-client-{{ pg_version }}"
      - python3-psycopg2
    state: present
    update_cache: true

- name: Listen on all interfaces
  lineinfile:
    path: "/etc/postgresql/{{ pg_version }}/main/postgresql.conf"
    regexp: '^#?\s*listen_addresses\s*='
    line: "listen_addresses = '*'"
  notify: restart postgres

- name: ACL CIDR in pg_hba.conf (md5)
  blockinfile:
    path: "/etc/postgresql/{{ pg_version }}/main/pg_hba.conf"
    marker: "# {mark} ansible app access"
    block: |
      {% for cidr in allow_cidrs %}
      host  all  all  {{ cidr }}  md5
      {% endfor %}
  notify: reload postgres

- name: Ensure PostgreSQL running/enabled
  service:
    name: "postgresql@{{ pg_version }}-main"
    state: started
    enabled: true

- name: Wait for 5432
  wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: 5432
    timeout: 20
